// ═══════════════════════════════════════════
// CLASS META
// ═══════════════════════════════════════════
const CM={
  light:        {name:'Light',        align:'Benevolent',areaName:'Shining Justice', areaM:8,  icon:'☀︎'},
  inferno:      {name:'Inferno',      align:'Malevolent',areaName:'Wildfire',        areaM:6,  icon:'🔥︎'},
  blizzard:     {name:'Blizzard',     align:'Benevolent',areaName:'Frozen Tundra',   areaM:5,  icon:'❄︎'},
  shadow:       {name:'Shadow',       align:'Malevolent',areaName:'Dark Domain',     areaM:8,  icon:'◆'},
  maximum:      {name:'Maximum',      align:'Benevolent',areaName:'Higher Ground',   areaM:9,  icon:'👑︎'},
  deckstructive:{name:'Deckstructive',align:'Malevolent',areaName:'Drawbridge',      areaM:8,  icon:'⚙'},
  negative:     {name:'Negative',     align:'Malevolent',areaName:'The Lowlands',    areaM:-9, icon:'▼'},
  restorative:  {name:'Restorative',  align:'Benevolent',areaName:'Halcyon Highlands',areaM:9, icon:'✚'},
  haste:        {name:'Haste',        align:'Benevolent',areaName:'Fast Track',      areaM:6,  icon:'🗲︎'},
  astute:       {name:'Astute',       align:'Benevolent',areaName:'The Library',     areaM:7,  icon:'⛬'},
  '7th':        {name:'7th',          align:'Neutral',   areaName:'Seven Heaven',    areaM:7,  icon:'☘'},
  zero:         {name:'Zero',         align:'Neutral',   areaName:'Dreadnaught Airship',areaM:0,icon:'∅'},
  phantom:      {name:'Phantom',      align:'Malevolent',areaName:'Morbid Cemetery', areaM:3,  icon:'☠'},
};
const AIPAIR={light:'inferno',inferno:'light',blizzard:'shadow',shadow:'blizzard',maximum:'negative',negative:'maximum',deckstructive:'blizzard',
  restorative:'phantom',phantom:'restorative',astute:'zero',zero:'astute',haste:'7th','7th':'haste'};
const CLASS_COLORS={
  light:'#FFFFFF',inferno:'#FF0000',blizzard:'#B3EEFF',shadow:'#000000',maximum:'#C09D2D',deckstructive:'#04825B',negative:'#3F1D53',
  restorative:'#FF6699',haste:'#FFE600',astute:'#940094','7th':'#B0C4DE',zero:'#8B6666',phantom:'#2B3E34',fission:'#42082B',extension:'#E67E22'
};
const CLASS_STATS={
  '7th':{off:6,def:6,acc:3,syn:7,dis:6,ver:4,res:6},
  phantom:{off:7,def:5,acc:3,syn:7,dis:6,ver:4,res:5},
  restorative:{off:4,def:7,acc:5,syn:7,dis:2,ver:3,res:7},
  shadow:{off:6,def:5,acc:3,syn:7,dis:7,ver:3,res:4},
  light:{off:5,def:6,acc:4,syn:6,dis:5,ver:3,res:6},
  blizzard:{off:2,def:7,acc:5,syn:6,dis:6,ver:2,res:5},
  zero:{off:3,def:7,acc:2,syn:7,dis:7,ver:3,res:4},
  haste:{off:7,def:4,acc:4,syn:6,dis:5,ver:2,res:4},
  negative:{off:4,def:6,acc:3,syn:6,dis:7,ver:2,res:4},
  astute:{off:3,def:5,acc:2,syn:6,dis:7,ver:3,res:5},
  deckstructive:{off:4,def:4,acc:4,syn:6,dis:6,ver:3,res:4},
  maximum:{off:7,def:4,acc:2,syn:7,dis:5,ver:3,res:3},
  inferno:{off:7,def:3,acc:4,syn:6,dis:5,ver:2,res:3}
};
const STAT_META=[
  {k:'off',abbr:'Off',name:'Offense',desc:'Measures how quickly and effectively a deck can pressure opponents through Morale damage, Casualty damage, or both.'},
  {k:'def',abbr:'Def',name:'Defense',desc:'Measures how well a deck protects itself from attacks, reduces damage, negates threats, and responds after being hit.'},
  {k:'acc',abbr:'Acc',name:'Accessibility',desc:'Measures how easy the deck is to learn, pilot, and master efficiently, with higher scores meaning more beginner-friendly.'},
  {k:'syn',abbr:'Syn',name:'Synergy',desc:'Measures how naturally the deck\'s cards work together for combos, setups, recovery, and maintaining momentum after disruption.'},
  {k:'dis',abbr:'Dis',name:'Disruption',desc:'Measures how well the deck interferes with the opponent\'s strategy, limits their options, and counters their counterplay.'},
  {k:'ver',abbr:'Ver',name:'Versatility',desc:'Measures how many different win conditions the deck can realistically and naturally pursue without forcing an awkward strategy.'},
  {k:'res',abbr:'Res',name:'Resources',desc:'Measures how efficiently the deck uses its hand, Deck, Bank, Drop, Deadzone, Morale, and recovery tools without running out of options.'}
];

// ═══════════════════════════════════════════
// ACTION CARD DATA
// ═══════════════════════════════════════════
const AC={
  Repair:       {name:'Repair',      sub:'Advantageous',M:1,e1:'Drop this card and a card from your Deadzone.',e2:'Death Draw: Drop this card.'},
  Plus:         {name:'Plus',        sub:'Advantageous',M:1,e1:'Drop this card. Your Rank Zone and Flank Zone cards gain 2 NP until end of turn.',e2:'Death Draw: (Casualty) Target opponent must take one Casualty Draw.'},
  Reverse:      {name:'Reverse',     sub:'Advantageous',M:1,e1:'Drop this card. The Death Draw effects of opponent\'s Action Cards are negated until end of turn.',e2:'Death Draw: (Casualty) All Casualty Draws after this go to the player that gave you this casualty until end of turn.'},
  Multiply:     {name:'Multiply',    sub:'Advantageous',M:3,e1:'Pay 2 MP, drop this card and top 2 of Deck. The NP of ALL Numerals on the Battlefield (both sides) are doubled until end of turn.',e2:'Death Draw: (Casualty) Send top 2 of Deck to Deadzone; opponent takes Casualty Draws equal to their casualty count.'},
  Explore:      {name:'Explore',     sub:'Advantageous',M:3,e1:'Drop this card, 2 from hand, top 2 of Deck, last 2 of Deck. Add one Area card from Deck or Drop to hand.',e2:'Death Draw: (Casualty) Send top of Deck to Deadzone; place one Area card on top of Deck. If opponent has Area in Deadzone, send it to Drop and they draw 1.'},
  Muster:       {name:'Muster',      sub:'Advantageous',M:0,e1:'Drop this card and your entire hand. Add one of every Numeral lower than your Rank Zone NP from your Deck to hand.',e2:'Death Draw: (Casualty) Drop top 4 of Deck. Add one of every Numeral lower than Rank Zone NP from your Deadzone to hand.'},
  Search:       {name:'Search',      sub:'Advantageous',M:2,e1:'Drop this card, one from hand, top of Deck and pay 3 MP. Add one card from your Deck to hand.',e2:'Death Draw: (Casualty) Send top 3 of Deck to Drop. Drop one from Deadzone; add one from Deck or Drop to hand.'},
  Reveal:       {name:'Reveal',      sub:'Advantageous',M:2,e1:'Drop this card, one from hand and last of Deck. Opponent shows hand; you may drop one card from their hand.',e2:'Death Draw: (Casualty) Send top of Deck to Drop. Opponent shows hand until end of turn; you may drop one from their hand.'},
  Spy:          {name:'Spy',         sub:'Advantageous',M:1,e1:'Drop this card and one from hand. See opponent\'s hand. Opponent cannot use Safeguard cards and you cannot use other Action Cards this turn.',e2:'Death Draw: (Casualty) Opponent must show their hand until end of turn.'},
  Set:          {name:'Set',         sub:'Advantageous',M:0,e1:'Drop this card, one from hand and one from Bank. Set one card from hand on top of your Deck.',e2:'Death Draw: (Drop) At end of turn you may set this card on top of your Deck.'},
  Protect:      {name:'Protect',     sub:'Safeguard',M:2,e1:'Damage Defense: When opponent declares an attack, drop this from hand. Take 1 less Casualty Damage; Flank Zone cards cannot be destroyed in battle this turn.',e2:'Casualty Counter: Drop this and one from hand. Drop one card from your Deadzone.'},
  Cease:        {name:'Cease',       sub:'Safeguard',M:3,e1:'Damage Defense: If opponent declared an attack, drop this from hand and negate that attack.',e2:'Casualty Counter: Drop this and 1 from Deadzone. All Casualty Draws after this are negated this turn.'},
  Recover:      {name:'Recover',     sub:'Safeguard',M:3,e1:'Damage Defense: Drop this card. During the End Phase of the turn this was used, add 1 card from your Deadzone to hand.',e2:'Casualty Counter: Drop this and 1 from Deadzone. Add one card from your Drop to hand.'},
  Return:       {name:'Return',      sub:'Safeguard',M:2,e1:'Damage Defense: (Drop) If a Numeral on your Battlefield would be defeated, shuffle 3 cards from Drop into Deck.',e2:'Casualty Counter: Drop this and 2 from hand. Shuffle 2 from Drop and 2 from Deadzone into Deck. Opponent draws 1.'},
  Reduce:       {name:'Reduce',      sub:'Safeguard',M:0,e1:'Damage Defense: When your Flank Zone card is targeted, drop this and last of Deck. Attacking card loses NP equal to its Rank until end of Battle Phase.',e2:'Casualty Counter: Drop this and one from hand.'},
  Divide:       {name:'Divide',      sub:'Safeguard',M:2,e1:'Damage Defense: After Damage Calculation, drop last of Deck. All Morale Damage taken this turn is halved.',e2:'Casualty Counter: Drop this and two from hand. Drop half of Deadzone cards.'},
  Counterattack:{name:'Counterattack',sub:'Retaliatory',M:-1,e1:'Avenging Attack: If opponent declared an attack, drop this. You may declare an attack with your Rank Zone card this turn.',e2:'Sabatoric Draw: (Casualty) Drop one from hand. Your Rank Zone can attack opponent this turn.'},
  Counterstrike:{name:'Counterstrike',sub:'Retaliatory',M:-2,e1:'Avenging Attack: If opponent defeated one of your Numerals this turn, drop this. Rank Zone gains 2 NP until end of your next turn; you may counterattack.',e2:'Sabatoric Draw: (Casualty) Target one card in opponent\'s Flank Zones. Send it to Deadzone; opponent loses 2 MP this turn.'},
  Strike:       {name:'Strike',      sub:'Retaliatory',M:-1,e1:'Avenging Attack: Drop this card. Target opponent loses 2 MP and takes 1 Casualty Draw.',e2:'Sabatoric Draw: (Casualty) Target opponent loses 2 MP and takes 1 Casualty Draw.'},
  Betray:       {name:'Betray',      sub:'Retaliatory',M:-3,e1:'Avenging Attack: After opponent attacks you, negate all Casualty Damage and send this to Deadzone. If you do, opponent\'s highest Numeral must attack their lowest.',e2:'Sabatoric Draw: (Casualty) Drop top 2 of your Deck. Send this and top of opponent\'s Deck to their Deadzone; negate its effects if Action Card.'},
  Subtract:     {name:'Subtract',    sub:'Retaliatory',M:-3,e1:'Avenging Attack: After opponent attacks you, negate all Morale Damage. Drop one from hand and top of Deck; opponent\'s Rank Zone loses NP equal to damage you would have taken.',e2:'Sabatoric Draw: Send this to opponent\'s Deadzone. Drop one from hand, Deadzone and top of Deck; opponent loses MP you lost this turn and you gain same amount.'},
  Discard:      {name:'Discard',     sub:'Retaliatory',M:-2,e1:'Avenging Attack: Opponent must drop cards from hand or top of Deck equal to Casualties you received this turn.',e2:'Sabatoric Draw: (Casualty) Opponent sends 2 from hand to Drop, or this goes to their Deadzone and they drop top of Deck.'},
  Deckstroy:    {name:'Deckstroy',   sub:'Retaliatory',M:-2,e1:'Avenging Attack: After opponent attacks you and deals Morale Damage, drop this. Opponent drops top 3 of Deck.',e2:'Sabatoric Draw: (Casualty) Send this to opponent\'s Deadzone. Opponent drops top 3 of Deck and loses 3 MP.'},
  'Rank Star':  {name:'Rank Star',   sub:'Advantageous',M:2,isStar:true,starType:'generic',e1:'Drop this card. All cards on your Battlefield gain 1 NP and Rank Zone gains 1 RP until end of turn.',e2:'Death Draw: (Drop) Other Casualty Draws against you after this are negated for rest of turn.'},
  'Battle Star':{name:'Battle Star', sub:'Advantageous',M:3,isStar:true,starType:'generic',e1:'Drop this and one from hand. All Numerals on your Battlefield gain 3 NP and 1 RP until end of turn.',e2:'Death Draw: Opponent takes 2 Casualty Draws.'},
  'Draw Star':  {name:'Draw Star',   sub:'Advantageous',M:2,isStar:true,starType:'generic',e1:'Drop this and one from hand. Draw 3 cards.',e2:'Sabatoric Draw: (Casualty) Discard one card and send top of Deck to Deadzone. Draw 3 cards.'},
  'Multi-Star': {name:'Multi-Star',  sub:'Advantageous',M:4,isStar:true,starType:'generic',e1:'Pay 3 MP, drop this and top 4 of Deck. RP and NP of all your Numerals on Battlefield are doubled until end of turn.',e2:'Death Draw: (Casualty) Send top 4 of Deck to Deadzone; opponent takes Casualty Draws equal to twice their casualty count.'},
  'Neo Rank Star':   {name:'Neo Rank Star',  sub:'Advantageous',M:3,isStar:true,starType:'neo',e1:'Drop this and 2 from Deadzone. Rank Zone gains 1 NP and 2 RP until end of turn.',e2:'Death Draw: (Drop) Drop 2 from Deadzone. Opponent takes 2 Casualty Draws this turn.'},
  'Neo Battle Star': {name:'Neo Battle Star', sub:'Advantageous',M:5,isStar:true,starType:'neo',e1:'Drop this, 1 from Deadzone and 2 from hand. Your Numerals gain 2 NP and 1 RP; opponent\'s Numerals lose 2 NP until end of turn.',e2:'Death Draw: (Casualty) Drop 2 from Deadzone and top of Deck. Opponent takes 2 Casualty Draws and loses 2 MP.'},
  'Neo Draw Star':   {name:'Neo Draw Star',   sub:'Advantageous',M:3,isStar:true,starType:'neo',e1:'(Drop) Drop 1 from Deadzone and 3 from hand. Draw 5 cards. Rank Zone gains 2 NP until end of turn.',e2:'Death Draw: Drop this, 1 from Deadzone and last 2 of Deck. Opponent mills 3; you draw 3.'},
  'Shining Star':  {name:'Shining Star', sub:'Advantageous',M:5,isStar:true,starType:'class',cls:'light',     e1:'Drop this card. All Light Numerals gain 2 NP; Malevolent Numerals lose 1 NP. Drop 1 from Deadzone after Battle Phase.',e2:'Death Draw: (Casualty) Drop 2 from Deadzone. Opponent takes Casualty Draws equal to Rank of highest Light Numeral dropped.'},
  'Burning Star':  {name:'Burning Star', sub:'Retaliatory', M:5,isStar:true,starType:'class',cls:'inferno',   e1:'Avenging Attack: Opponent loses MP equal to highest Numeral they control. Rank Zone gains same NP until end of turn; you may counterattack.',e2:'Sabatoric Draw: (Casualty) Opponents lose MP equal to number of cards in their Deadzone.'},
  'Freezing Star': {name:'Freezing Star',sub:'Safeguard',   M:5,isStar:true,starType:'class',cls:'blizzard',  e1:'Damage Defense: Target the attacking Numeral and negate the attack. Both players gain Morale equal to the Numeral whose attack was negated.',e2:'Casualty Counter: Drop this and 2 from Deadzone. You cannot take Casualty Damage for turns equal to Rank of Numeral that attacked you this turn.'},
  'Shaded Star':   {name:'Shaded Star',  sub:'Advantageous',M:5,isStar:true,starType:'class',cls:'shadow',    e1:'Drop this card. Rank and Flank Zone cards gain NP equal to lowest card on Battlefield and 2 RP until end of turn.',e2:'Death Draw: (Drop) Drop 3 from Deadzone. Opponent takes 3 Casualty Draws and Morale is halved.'},
  'MAX Star':      {name:'MAX Star',     sub:'Advantageous',M:5,isStar:true,starType:'class',cls:'maximum',   e1:'Drop this card. Both players drop 1 from Deadzone. Your Numerals gain 2 NP and 2 RP until end of turn.',e2:'Death Draw: Drop this. Both drop 2 from Deadzone; opponent loses MP equal to RP of highest card on Battlefield.'},
  'Drop Star':     {name:'Drop Star',    sub:'Retaliatory', M:5,isStar:true,starType:'class',cls:'deckstructive',e1:'Avenging Attack: If your Numeral was defeated in battle this turn, Rank Zone gains 3 NP for counterattack; if successful, opponent\'s top 5 go to Drop.',e2:'Sabatoric Draw: (Casualty) Opponent drops 1 from hand and cards from Deck equal to their Casualty count.'},
  'Minus Star':    {name:'Minus Star',   sub:'Retaliatory', M:5,isStar:true,starType:'class',cls:'negative',  e1:'Avenging Attack: Drop this. Opponent sends 1 Bank card to Deadzone; if they do, they lose MP equal to the Numeral they attacked this turn.',e2:'Sabatoric Draw: Send this to Deadzone. Opponent\'s 2 highest Numerals in hand go to Deadzone; they lose MP equal to their Ranks.'},
  // ── New-class action cards ──
  Motivate:     {name:'Motivate',    sub:'Advantageous',M:2,e1:'Drop this and 3 from hand. Gain Morale equal to the highest Numeral on the Battlefield.',e2:'Death Draw: Select two Rank 2 or lower Numerals in your Deadzone. Send one to Drop, add one to hand. Gain Morale equal to the Rank of the lower one.'},
  Boost:        {name:'Boost',       sub:'Advantageous',M:2,e1:'Drop this and top 2 of Deck. Your Rank Zone gains 4 NP until end of turn.',e2:'Drop one from Deadzone. Rank Zone gains NP equal to the dropped card\'s RP until end of turn.'},
  Draw:         {name:'Draw',        sub:'Advantageous',M:1,e1:'Drop this card. Draw one card.',e2:'Draw one card.'},
  Wander:       {name:'Wander',      sub:'Advantageous',M:0,e1:'Drop this. Mill until you mill an Area Card; add it to hand. Gain 1 MP per card milled.',e2:'Cede one from Bank. Reveal from Deck until an Area Card; add it to hand; bottom the rest.'},
  Reanimate:    {name:'Reanimate',   sub:'Advantageous',M:2,e1:'Discard this and one Numeral from hand; mill 1. Send one Rank2 Numeral 6 or lower from Deadzone to your Flank Zone (its M becomes 0 this turn).',e2:'Drop this and one Numeral from Deadzone; mill 1. Send one Rank2 Numeral 6 or lower from Deadzone to your Flank Zone.'},
  Recycle:      {name:'Recycle',     sub:'Safeguard',M:2,e1:'Damage Defense: When a Classed Flank card is ceded, mill 2. Return it to Deck and add a Classless Numeral of equal NP from any location to hand.',e2:'Casualty Counter: Add a Classless Numeral of equal NP from any location to hand.'},
  Nullify:      {name:'Nullify',     sub:'Safeguard',M:0,e1:'Damage Defense: Discard this. Negate all Morale and Casualty Damage this turn.',e2:'Casualty Counter: (Casualty) Drop all Casualty Draws given to you this turn at end of turn.'},
  Assassinate:  {name:'Assassinate', sub:'Retaliatory',M:-2,e1:'Avenging Attack: Drop this and one from hand. Opponent must send one card from their hand to the Deadzone.',e2:'Sabatoric Draw: (Casualty) Opponent sends one card from their hand to the Deadzone.'},
  Revive:       {name:'Revive',      sub:'Safeguard',M:3,e1:'Damage Defense: (Drop) At end of Battle Phase, target one Numeral in Deadzone and drop top of Deck. Flank with it and gain MP equal to its Rank.',e2:'Casualty Counter: Flank with one Rank 2 or lower Numeral from Deadzone. Gain Morale equal to half the Morale you lost this turn.'},
  'Halcyon Star':{name:'Halcyon Star',sub:'Advantageous',M:5,isStar:true,starType:'class',cls:'restorative',e1:'Drop this and 3 Restorative Numerals in Deadzone. Rank Zone gains NP equal to half your Morale until end of turn. All players draw 1 at end of turn.',e2:'Death Draw: Drop/Add three from Deadzone to hand. All other players add one from their Deadzone to hand and draw 1.'},
  'Studious Star':{name:'Studious Star',sub:'Advantageous',M:5,isStar:true,starType:'class',cls:'astute',e1:'Attacking Advantage: Look at top 5 of an opponent\'s Deck. Drop 1 and place the rest on top in any order. Draw 1 at end of turn.',e2:'Death Draw: (Drop) Look at top 5 of a Deck; use the Secondary effect of one Action Card among them, then send all 5 to Drop.'},
  'Track Star': {name:'Track Star',  sub:'Advantageous',M:5,isStar:true,starType:'class',cls:'haste',e1:'Drop this and one Haste Numeral in Deadzone. Rank Zone gains 4 NP until end of turn. If opponent lost 6+ MP this turn, attack again.',e2:'Death Draw: Drop bottom Deadzone card. If a Numeral, Rank Zone gains 2 NP and may attack opponent this turn.'},
  'Haunting Star':{name:'Haunting Star',sub:'Retaliatory',M:5,isStar:true,starType:'class',cls:'phantom',e1:'Avenging Attack: If you took a Casualty from an attack this turn, drop this. Rank Zone gains 2 RP and can attack opponent directly this turn.',e2:'Sabatoric Draw: (Drop) Add up to 3 Phantom Numerals from Deadzone to hand. Opponent takes 5 Casualty Draws this turn.'},
  'Seventh Star':{name:'Seventh Star',sub:'Advantageous',M:5,isStar:true,starType:'class',cls:'7th',e1:'Drop this. If a Numeral 7 is in your hand or Battlefield, all your Numerals become Rank 7 until end of turn.',e2:'Sabatoric Draw: (Drop) If a Numeral 7 is in your Deadzone, opponent drops 7 from hand and/or Deck at end of turn.'},
  'Naught Star':{name:'Naught Star', sub:'Safeguard',M:5,isStar:true,starType:'class',cls:'zero',e1:'Damage Defense: When opponent attacks a Zero Numeral, drop this and one Zero Numeral from hand. Negate the attack.',e2:'Casualty Counter: If Dreadnaught Airship is in your Deadzone, take no Casualty Damage next turn.'},
};

// ═══════════════════════════════════════════
// NUMERAL DATA
// ═══════════════════════════════════════════
const ND={
 light:[
  {n:0,r:0,A:0,M:0,S:0,ca:false,st:'Skilled',sc:'Discard a card from hand.',sk:'Take no Morale or Casualty Damage from attacks involving this card until end of turn.'},
  {n:1,r:1,A:1,M:1,S:0,ca:true,st:'Skilled',sc:'Send this card to the bottom of your deck.',sk:'Add one Light-class card from your deck to your hand.'},
  {n:2,r:1,A:1,M:1,S:2,ca:true,st:'Skilled',sc:'Send this card from Bank to Deadzone.',sk:'Your Rank Zone card gets another attack this turn.'},
  {n:3,r:1,A:1,M:1,S:99,ca:true,st:'Skilled',sc:'Discard this card.',sk:'If a Numeral on your field is being attacked, negate the attack and return that Numeral to your hand. Lose MP equal to RP of the returned card.'},
  {n:4,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},{n:5,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:6,r:2,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'This card must be on battlefield and another you control must be targeted. Discard a card from hand.',sk:'Negate all Morale Damage from attacks involving this card for rest of turn.'},
  {n:7,r:3,A:2,M:3,S:5,ca:true,st:'Skilled',sc:'Drop a card from hand and Bank; NP total ≥7.',sk:'Drop 2 from your Deadzone; opponent drops 1 from their Deadzone. Cannot attack this turn.'},
  {n:8,r:3,A:2,M:3,S:2,ca:true,st:'Skilled',sc:'Drop 2 from hand and top 2 of deck.',sk:'Invest 2 Light-class Numerals from your Discard. Cannot attack this turn.'},
  {n:9,r:3,A:2,M:3,S:99,ca:true,st:'Skilled',sc:'(Skill 1) No cost. (Skill 2) Light 0 in Bank + Shining Justice in Deadzone; drop hand.',sk:'(Skill 1) Can only attack/be attacked by Rank³+. (Skill 2) Gains NP equal to RP total of Light Numerals in Bank; gain same MP; attack up to Flank Zone count times; Stand Down one Flank after each attack.'},
 ],
 inferno:[
  {n:0,r:0,A:0,M:0,S:-1,ca:false,st:'Skilled',sc:'This card must be in Bank; Drop one card.',sk:'Negate all Morale Damage from first effect of Wildfire.'},
  {n:1,r:1,A:1,M:1,S:1,ca:true,st:'Skilled',sc:'Send this card from hand or battlefield to Deadzone.',sk:'Send one Wildfire to your Deadzone.'},
  {n:2,r:1,A:1,M:1,S:2,ca:true,st:'Skilled',sc:'Send this card from Bank to Deadzone.',sk:'Your Rank Zone card gets another attack this turn.'},
  {n:3,r:1,A:1,M:1,S:2,ca:true,st:'Skilled',sc:'Send this card to the Deadzone.',sk:'Your opponents lose 3 MP.'},
  {n:4,r:2,A:1,M:2,S:2,ca:true,st:'Skilled',sc:'Send this card from hand or Bank to Deadzone.',sk:'Rank Zone gets another attack this turn. At end of Damage Step, opponents lose 3 MP.'},
  {n:5,r:2,A:1,M:-1,S:null,ca:true,st:'Basic',sk:'No skill.'},{n:6,r:2,A:1,M:-1,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:7,r:3,A:2,M:-3,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:8,r:3,A:2,M:3,S:99,ca:true,st:'Skilled',sc:"Send random card from Bank to Deadzone. Discard from hand cards with NP total ≥ 8 + that card's NP.",sk:"Attack up to that card's Numeral times. Gain MP equal to its NP after 2 successful attacks; opponent loses MP equal to RP of attacked card after every successful attack."},
  {n:9,r:3,A:2,M:3,S:6,ca:true,st:'Skilled',sc:'Select card from hand and 2 from Bank; NP total >9. Drop lowest 2, send highest to Deadzone.',sk:'Opponent loses MP = lowest card Rank × RP total of 2 highest cards. Cannot attack this turn.'},
 ],
 blizzard:[
  {n:0,r:0,A:0,M:0,S:0,ca:false,st:'Skilled',sc:'Drop top card of your deck.',sk:"Once per turn, target the card attacking this card. That card cannot attack until end of opponent's next turn."},
  {n:1,r:1,A:1,M:1,S:0,ca:true,st:'Skilled',sc:'Return this card from hand or Battlefield into your deck.',sk:'Add 1 Safeguard-type Action Card from your deck to your hand.'},
  {n:2,r:1,A:1,M:1,S:2,ca:true,st:'Skilled',sc:'Cede this card from your Bank.',sk:"Opponent's Rank Zone loses 1 NP and cannot attack until end of their next turn."},
  {n:3,r:1,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},{n:4,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:5,r:2,A:1,M:2,S:2,ca:true,st:'Skilled',sc:'Mill one card when this card attacks.',sk:"If milled card is a Blizzard-class Numeral, the Numeral you're attacking loses 2 NP until end of turn."},
  {n:6,r:2,A:1,M:-2,S:-2,ca:true,st:'Skilled',sc:'Mill 2 cards. Drop one from hand and Deadzone.',sk:"Neither player can declare an attack until end of turn. Target opponent drops one from Deadzone at end of turn."},
  {n:7,r:3,A:2,M:3,S:4,ca:true,st:'Skilled',sc:'Drop one from Bank, one from hand, mill one; NP total ≥7.',sk:'If milled card was an Action Card, add 2 Safeguard Action Cards from deck to hand; neither player takes damage until end of your next turn.'},
  {n:8,r:3,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:9,r:3,A:2,M:3,S:4,ca:true,st:'Skilled',sc:"Mill 3 cards. Drop 2 Numerals from hand with NP total ≥9. Cede one from Bank.",sk:"Place one Blizzard Cipher¹ Digit 1 in an open Flank Zone of opponent's. That Digit cannot Stand Down, be relieved, or be destroyed for turns equal to RP of the Numeral sent to Deadzone."},
 ],
 shadow:[
  {n:0,r:0,A:2,M:0,S:2,ca:false,st:'Skilled',sc:'Drop 1 card from hand when this card attacks.',sk:'Use the second effect of an Advantageous Action Card instead of the first.'},
  {n:1,r:1,A:1,M:1,S:0,ca:true,st:'Skilled',sc:'Send this card back into your Deck.',sk:"Add one non-Star Card Shadow-class card from your Deck to your hand."},
  {n:2,r:1,A:1,M:1,S:2,ca:true,st:'Skilled',sc:'Cede this card from your Bank.',sk:'Your Rank Zone card gets another attack this turn.'},
  {n:3,r:1,A:1,M:1,S:3,ca:true,st:'Skilled',sc:"Drop cards from hand with NP equal to or higher than the targeted Numeral.",sk:"Take control of that target as a Flank Zone card. Drop 3 from hand at end of every turn to maintain, or send it to opponent's Deadzone."},
  {n:4,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},{n:5,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:6,r:2,A:1,M:2,S:4,ca:true,st:'Skilled',sc:"When opponent uses a Numeral skill, drop cards from hand with NP total ≥6 + that Numeral (after they pay cost).",sk:"Negate that card's skill(s) until end of opponent's next turn. That Numeral cannot attack the turn you use this skill."},
  {n:7,r:3,A:2,M:3,S:3,ca:true,st:'Skilled',sc:'Drop one from hand and Bank; NP total ≥7.',sk:'Drop one from your Deadzone; opponent takes one Casualty Draw. Cannot attack this turn.'},
  {n:8,r:3,A:2,M:3,S:99,ca:true,st:'Skilled',sc:"Cede random card from Bank. Discard from hand cards with NP total ≥ 8 + that card's NP.",sk:"Attack up to that card's Numeral times. Gain MP equal to that card. Gains NP equal to attacked Numeral after every 3 attacks."},
  {n:9,r:3,A:2,M:3,S:4,ca:true,st:'Skilled',sc:"Drop 2 from hand and cede 1 from Bank; NP total ≥9.",sk:"When you declare an attack, negate second effects of opponent's Advantageous Action Cards. If opponent receives an Action Card during Damage Step, its Morale Boost is subtracted instead."},
 ],
 maximum:[
  {n:0,r:0,A:0,M:1,S:0,ca:false,st:'Skilled',sc:'No cost.',sk:'Once per game, during Battle Phase, this card is treated as Rank MAX until end of turn.'},
  {n:1,r:1,A:1,M:2,S:1,ca:true,st:'Skilled',sc:'Drop this card from hand or Battlefield.',sk:'Add 1 Area card from your deck to hand. Cannot use Action Cards until end of your next turn.'},
  {n:2,r:1,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'Cede this card from Bank. Mill one card.',sk:'Your Rank Zone and one Flank Zone each get another attack this turn.'},
  {n:3,r:1,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},{n:4,r:2,A:1,M:3,S:4,ca:true,st:'Skilled',sc:'Cede this card from Bank. Mill 2 cards.',sk:'All Numerals on your Battlefield get another attack this turn.'},
  {n:5,r:2,A:1,M:3,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:6,r:2,A:1,M:3,S:4,ca:true,st:'Skilled',sc:'Cede this card from Bank. Mill 3 cards.',sk:'All Numerals on your Battlefield get another attack this turn and gain 1 NP until end of turn.'},
  {n:7,r:3,A:2,M:4,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:8,r:3,A:2,M:4,S:99,ca:true,st:'Skilled',sc:"Send random card from Bank to Deadzone. Discard from hand cards with NP total ≥ 8 + that card's NP.",sk:"Attack up to that card's Numeral times. Gain MP equal to its NP after 2 successful attacks."},
  {n:9,r:3,A:2,M:4,S:null,ca:true,st:'Basic',sk:'No skill.'},
  // RANK MAX cards (n:10, 11, 12) — obtained via Maximum Rank Up. Stats per official data; their advanced skills are not yet implemented.
  {n:10,r:4,A:3,M:5,S:5,ca:true,st:'Skilled',sc:'When you declare an attack with this Numeral, you may drop 5 cards from your hand whose NP total is at least 25, then drop the top 5 cards of your Deck.',sk:'Use either effect of any Action Card dropped from this skill (this turn). You cannot use your Attacking Advantage the turn you use this skill. (Rank MAX)'},
  {n:11,r:4,A:3,M:5,S:99,ca:true,st:'Skilled',sc:'(Skill 1) Drop hand cards with NP total = 11, declare an Action type, drop top 3 of Deck. (Skill 2) If a Numeral 7 is in your Bank, drop 2 from hand.',sk:'(Skill 1) If the declared type is among the 3, add them to hand and use their effects free this turn; gain MP = highest Numeral used for cost. Else drop 1 from Bank and lose that MP. (Skill 2) Drop 2 from Deadzone. You cannot attack the turn you use this skill. (Rank MAX)'},
  {n:12,r:4,A:3,M:6,S:99,ca:true,st:'Skilled',sc:'(Skill 1) Send a card from your hand to the Deadzone. (Skill 2) If you have 6+ cards in hand, discard your hand.',sk:'(Skill 1) Your Advantageous Action Card effects are multiplied by the sent card Rank this turn; gain Morale = half its NP. (Skill 2) Use the skills of up to 2 Skilled Maximum Numerals in your Bank without paying their costs this turn. (Rank MAX)'},
 ],
 deckstructive:[
  {n:0,r:0,A:0,M:0,S:2,ca:false,st:'Skilled',sc:'Drop 3 cards from hand.',sk:'Once per turn when this card is targeted for attack, negate the attack. After Battle Phase, the attacking player mills cards equal to the NP of the card that would have attacked.'},
  {n:1,r:1,A:1,M:1,S:0,ca:true,st:'Skilled',sc:'Switchdraw this card from hand.',sk:'Add one Area card from your Deck to your hand.'},
  {n:2,r:1,A:1,M:2,S:2,ca:true,st:'Skilled',sc:'Drop this card from Bank.',sk:'Rank Zone gets another attack this turn. Opponent takes no Casualty Damage but must mill 2 cards for each casualty they would have taken.'},
  {n:3,r:1,A:1,M:2,S:-3,ca:true,st:'Skilled',sc:'Cede this card from hand or Battlefield.',sk:'All other players must mill 3 cards from their Deck.'},
  {n:4,r:2,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'Cede this card from hand or Battlefield and cede a Rank 2+ Numeral from hand.',sk:'All players draw 3 cards; opponents drop all Action Cards they drew from this skill.'},
  {n:5,r:2,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:6,r:2,A:1,M:-3,S:null,ca:true,st:'Basic',sk:'No skill. Drop last 2 cards of your Deck when this card enters the Battlefield.'},
  {n:7,r:3,A:2,M:3,S:3,ca:true,st:'Skilled',sc:'Drop one from hand and Bank, then drop one from Deadzone.',sk:'Opponents mill cards equal to Rank of card dropped from Deadzone; you draw one card. Cannot attack this turn.'},
  {n:8,r:3,A:2,M:4,S:99,ca:true,st:'Skilled',sc:'Cede random card from Bank, then drop from hand cards with NP total >14.',sk:'Attack up to that Numeral times. Instead of Morale Damage, opponent mills 2 cards per MP they would have lost after each attack. Gain MP equal to cards opponent dropped after 3 successful attacks.'},
  {n:9,r:3,A:2,M:4,S:null,ca:true,st:'Basic',sk:'No skill.'},
  // RANK MAX cards (n:10, 11, 12) — obtained via Maximum Rank Up
  {n:10,r:4,A:2,M:5,S:null,ca:true,st:'Basic',sk:'No skill. Rank MAX: requires Maximum Rank Up (Stand Down Rank¹+Rank³ from Bank with combined NP≥10).'},
  {n:11,r:4,A:2,M:6,S:null,ca:true,st:'Basic',sk:'No skill. Rank MAX.'},
  {n:12,r:4,A:3,M:7,S:null,ca:true,st:'Basic',sk:'No skill. Rank MAX.'},
 ],
 negative:[
  {n:0,r:0,A:0,M:0,S:99,ca:false,st:'Skilled',sc:'Drop 1 card from hand.',sk:'Once per turn, when this card is targeted for attack, gain Morale equal to the Numeral that defeats this card in battle.'},
  {n:1,r:1,A:1,M:1,S:-1,ca:true,st:'Skilled',sc:'Drop this card from hand or Battlefield.',sk:"Add 1 Area card from your Deck to hand. If opponent has an Area card in hand, they must send it back into their Deck."},
  {n:2,r:1,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'Cede this card from Bank and mill one card.',sk:"Your Rank Zone gets another attack this turn; opponent's Rank Zone gains -2 NP until end of turn."},
  {n:3,r:1,A:1,M:2,S:-2,ca:true,st:'Skilled',sc:'Cede this card from hand or Battlefield and mill one card.',sk:"Target one Numeral on opponent's Battlefield. That Numeral gains -3 NP until end of their next turn."},
  {n:4,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:5,r:2,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'Cede this card from Bank, then mill 2 cards.',sk:"All Numerals on opponent's Battlefield gain -3 NP until end of turn."},
  {n:6,r:2,A:-1,M:-2,S:null,ca:true,st:'Basic',sk:'No skill. Send an Action Card from hand back to Deck when you declare an attack with this card, or when this card is defeated in battle.'},
  {n:7,r:3,A:2,M:3,S:4,ca:true,st:'Skilled',sc:'Cede this card from Bank and mill 3 cards.',sk:"All Numerals on all other players' Battlefields gain -3 NP and -1 RP until end of turn."},
  {n:8,r:3,A:2,M:-3,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:9,r:3,A:2,M:3,S:5,ca:true,st:'Skilled',sc:'Select 2 from Bank and 2 from hand. Cede highest, drop the rest.',sk:'All opponent Battlefield Numerals lose NP equal to Numeral sent to Deadzone. All players add 1 from Deadzone to hand; cannot use it until end of your next turn.'},
 ],
 restorative:[
  {n:0,r:0,A:1,M:5,S:2,ca:true,st:'Skilled',sc:'Once per turn, when your opponent declares an attack on this card, you may drop one card from your hand and the top card of your Deck.',sk:'Negate all Casualty Damage from that attack.'},
  {n:1,r:1,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'Drop this card.',sk:'Add two Rank 2 or lower Restorative Numerals from your Deck to your hand. All other players draw one card and gain 2 Morale.'},
  {n:2,r:1,A:1,M:2,S:2,ca:true,st:'Skilled',sc:'Send this card from the Bank to the Drop.',sk:'The card in your Rank Zone gets another attack this turn.'},
  {n:3,r:1,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'No cost.',sk:'You may add this card from your Deadzone or Drop to your hand. If from your Deadzone, gain an additional 3 Morale. You take no additional Casualty Damage from attacks involving this card.'},
  {n:4,r:2,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:5,r:2,A:1,M:3,S:2,ca:true,st:'Skilled',sc:'When this card is involved in an attack, you may send the top card of your Deck to the Drop.',sk:'Gain MP equal to the Rank of the Numeral being attacked this turn.'},
  {n:6,r:2,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:7,r:3,A:2,M:5,S:4,ca:true,st:'Skilled',sc:'Once per turn, send one card from your hand and Bank to the Drop. The NP total between them must be 7 or more.',sk:'Drop 2 from your Deadzone and draw one. All other players drop one from their Deadzone, draw one and gain 3 Morale. You cannot attack the turn you use this skill.'},
  {n:8,r:3,A:2,M:5,S:8,ca:true,st:'Skilled',sc:'Once per turn, drop 3 cards from your hand and send the top 8 cards of your Deck to the Drop.',sk:'This card can attack up to as many times as the Numeral of the highest Restorative Numeral sent to the Drop, and gains NP equal to the Rank of the highest Numeral dropped, until end of turn.'},
  {n:9,r:3,A:1,M:5,S:null,ca:true,st:'Basic',sk:'No skill.'},
 ],
 astute:[
  {n:0,r:0,A:1,M:0,S:-2,ca:true,st:'Skilled',sc:'Discard a card.',sk:'When an opponent declares an attack on this card, you may discard a card; if you do, that opponent reveals their hand until end of turn and you may discard one card from their hand.'},
  {n:1,r:1,A:1,M:1,S:1,ca:true,st:'Skilled',sc:'Send this card from your hand or Battlefield to the Drop.',sk:'Look at target opponent\'s hand. Add an Astute Numeral from your Deck to your hand of equal value as a card in their hand.'},
  {n:2,r:1,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:3,r:1,A:1,M:2,S:-2,ca:true,st:'Skilled',sc:'Send this card from your hand or Battlefield to the Drop.',sk:'Look at the top 3 cards of target opponent\'s Deck. Place them back in any order.'},
  {n:4,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:5,r:2,A:1,M:3,S:-3,ca:true,st:'Skilled',sc:'Send this card from your hand or Battlefield to the Drop.',sk:'Look at the top 5 cards of target opponent\'s Deck. Drop 2 and place the rest back in any order.'},
  {n:6,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:7,r:3,A:2,M:3,S:4,ca:true,st:'Skilled',sc:'Once per turn, drop a card from your hand and Bank whose combined NP total is 7 or more, then drop one card from your Deadzone.',sk:'Target opponent reveals their hand; you may drop cards from their hand equal to the Rank of the card dropped from your Deadzone.'},
  {n:8,r:3,A:2,M:4,S:-4,ca:true,st:'Skilled',sc:'Draw 2, mill 4, and send a card from your Bank to the Deadzone.',sk:'Target opponent reveals top 8 of Deck. Choose 2 to add to their hand, 2 to discard, place the rest back. You cannot attack the turn you use this skill.'},
  {n:9,r:3,A:2,M:5,S:5,ca:true,st:'Skilled',sc:'Send one card from your hand and Bank to the Deadzone whose combined NP total is more than 10.',sk:'Target player reveals hand and top 9 of Deck. Add cards equal to the lowest Numeral used to their hand, place the rest back. You cannot attack the turn you use this skill.'},
 ],
 zero:[
  {n:0,r:0,A:3,M:0,S:2,ca:true,st:'Skilled',sc:'Once per turn, when this card would take Morale or Casualty Damage, discard one Zero-class card from your hand.',sk:'This card takes no Morale or Casualty Damage from that attack.'},
  {n:1,r:1,A:1,M:0,S:2,ca:true,st:'Skilled',sc:'Send this card from your hand or Battlefield to the Drop.',sk:'Add one Zero-class Numeral from your Deck to your hand. Its M value becomes 0 the turn it enters the Battlefield.'},
  {n:2,r:1,A:1,M:2,S:2,ca:true,st:'Skilled',sc:'Send this card from your Bank to the Deadzone and discard one card from your hand with Rank equal to the Numeral being attacked.',sk:'Your Rank Zone gets another attack this turn. If that attack would deal Casualty Damage, that Casualty Damage becomes 0.'},
  {n:3,r:1,A:2,M:0,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:4,r:2,A:1,M:2,S:2,ca:true,st:'Skilled',sc:'During the Battle Phase, when you declare an attack, discard this card from your hand and mill one card.',sk:'The card in your opponent\'s Rank Zone has its A value become 0 until end of their next turn.'},
  {n:5,r:2,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:6,r:2,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'Send this card and one Zero-class card from your Bank to the Deadzone.',sk:'During your opponent\'s next Draw Phase, they draw 0 instead of 2. This card is then treated as Basic until returned to your Deck.'},
  {n:7,r:3,A:2,M:5,S:null,ca:true,st:'Basic',sk:'No skill. If this enters the Battlefield by any method other than Promoting/Relieving a Zero-class Numeral, its Numeral and NP become 0 until end of turn.'},
  {n:8,r:3,A:1,M:2,S:4,ca:true,st:'Skilled',sc:'Once per turn, select a random card from your Bank. Drop hand cards whose total NP is at least 8 + the RP of the selected card, then send the selected card to the Deadzone.',sk:'This card can attack additionally up to the Rank of the card sent to the Deadzone. It deals 0 Morale Damage this turn. Each Numeral it attacks has its A value become 0 until you take damage from this card.'},
  {n:9,r:3,A:2,M:3,S:99,ca:true,st:'Skilled',sc:'(Skill 1) Drop hand cards totalling at least 9 + opponent Rank Zone NP, then cede top of both Decks. (Skill 2) When this attacks while both have A 0, cede one Rank2 from hand.',sk:'(Skill 1) That opponent cannot gain Morale for turns equal to their Rank Zone Rank; this card\'s A becomes 0 next turn. (Skill 2) The attacked Numeral becomes 0 until end of next turn.'},
 ],
 haste:[
  {n:0,r:0,A:2,M:0,S:1,ca:true,st:'Skilled',sc:'Once per turn, when this card is targeted for an attack, drop the top card of your Deck.',sk:'Add one Fast Track from your Drop or Deck to your hand.'},
  {n:1,r:1,A:1,M:1,S:0,ca:true,st:'Skilled',sc:'During your opponent\'s turn, send this card from your hand or Drop back into the Deck.',sk:'Add one non-Star Haste-class card to your hand.'},
  {n:2,r:1,A:1,M:1,S:2,ca:true,st:'Skilled',sc:'At the start of your opponent\'s turn, send this card from your Bank to the Deadzone and drop the top 2 cards of your Deck.',sk:'The card in your Rank Zone may attack your opponent this turn.'},
  {n:3,r:1,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:4,r:2,A:1,M:2,S:2,ca:true,st:'Skilled',sc:'After your opponent\'s Draw Phase, while in your Rank Zone; send this card to your Deadzone after the attack. You may drop one from hand and top of Deck.',sk:'This card can attack your opponent directly. If you pay the extra cost, you may use one Advantageous Action Card when you attack.'},
  {n:5,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:6,r:2,A:1,M:3,S:3,ca:true,st:'Skilled',sc:'Once per exchange during your opponent\'s turn, drop the last 4 cards of your Deck.',sk:'This card\'s NP and RP are cut in half, but it can attack your opponent directly this turn. If successful, add one Haste Numeral to your hand or Bank.'},
  {n:7,r:3,A:2,M:3,S:4,ca:true,st:'Skilled',sc:'Once per turn during your opponent\'s turn while in your Rank Zone or Bank, send one card from your hand and Bank to the Drop if the NP value is higher than 8.',sk:'Add up to two Haste Numerals from your Deadzone to your hand. You cannot use any other Numeral Skills the turn you use this skill.'},
  {n:8,r:3,A:2,M:4,S:99,ca:true,st:'Skilled',sc:'Once per exchange, send a random card from your Bank to the Deadzone, then drop hand/Flank cards whose NP total is 16 or higher.',sk:'You may negate all Safeguard Action Cards until end of turn. This card may attack up to the Numeral sent to the Deadzone, gaining 2 NP after each attack.'},
  {n:9,r:3,A:2,M:2,S:null,ca:true,st:'Basic',sk:'No skill. Must be Ranked Up from a Numeral 7 or higher during your Promotion Phase.'},
 ],
 phantom:[
  {n:0,r:0,A:1,M:0,S:2,ca:true,st:'Skilled',sc:'When this card is targeted for an attack, send the top card of your Deck to the Drop.',sk:'Send cards from your opponent\'s hand to their Deadzone equal to your Casualty Count.'},
  {n:1,r:1,A:1,M:1,S:1,ca:true,st:'Skilled',sc:'During your turn, send this card from your Battlefield or Deadzone to the Drop.',sk:'Add one Phantom card from your Deck to your hand. If you do, all other players send the last card of their Deck to the Deadzone (not a Casualty Draw).'},
  {n:2,r:1,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:3,r:1,A:1,M:2,S:-3,ca:true,st:'Skilled',sc:'Send this card to the Deadzone.',sk:'Send the top three cards of target player\'s Deck to the Deadzone (not a Casualty Draw).'},
  {n:4,r:2,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'When you declare an attack with this card, send the top card of your Deck to the Drop.',sk:'If that card was a Phantom card, this card can attack your opponent directly this turn.'},
  {n:5,r:2,A:1,M:0,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:6,r:2,A:1,M:2,S:3,ca:true,st:'Skilled',sc:'No cost.',sk:'When you declare an attack with this card, you may add one Rank 2 or lower Phantom Numeral from your Deadzone to your hand. If the attack was unsuccessful, return that card to the Deadzone.'},
  {n:7,r:3,A:0,M:2,S:null,ca:true,st:'Basic',sk:'No skill. Cannot be targeted by the Primary Effects of Safeguard Action Cards.'},
  {n:8,r:3,A:2,M:4,S:6,ca:true,st:'Skilled',sc:'Once per turn, send a random card from the Bank to the Deadzone, then drop hand cards whose NP total is 15 or more.',sk:'This card can attack up to the Numeral sent to the Deadzone. It gains 1 NP and RP equal to the Rank of the card sent, after every 2 attacks, until end of turn.'},
  {n:9,r:3,A:2,M:4,S:-9,ca:true,st:'Skilled',sc:'Once per turn during your Main Phase, send a Phantom Numeral from your hand or Bank to the Deadzone and drop cards from the top of your Deck equal to its Numeral.',sk:'Target opponent takes Casualty Draws and loses Morale equal to the Numeral sent to the Deadzone. Draw one card.'},
 ],
 '7th':[
  {n:0,r:0,A:0,M:0,S:null,ca:false,st:'Basic',sk:'No skill. Cannot attack.'},
  {n:1,r:1,A:1,M:1,S:0,ca:true,st:'Skilled',sc:'No cost.',sk:'Send this card to the bottom of your Deck. Place one Numeral 7 card on top of your Deck.'},
  {n:2,r:1,A:1,M:1,S:2,ca:true,st:'Skilled',sc:'Send this card from the Bank to the Deadzone.',sk:'The card in your Rank Zone gets another attack this turn.'},
  {n:3,r:1,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:4,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:5,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:6,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:7,r:3,A:1,M:2,S:1,ca:true,st:'Skilled',sc:'Drop one card from your hand.',sk:'Search your Deck for a Numeral 7 card and add it to your hand. (One of several Numeral-7 variants; full variant set + win condition queued.)'},
  {n:8,r:3,A:2,M:3,S:null,ca:true,st:'Basic',sk:'No skill.'},
  {n:9,r:3,A:2,M:3,S:null,ca:true,st:'Basic',sk:'No skill.'},
 ],
};

const CLASSLESS=[
 {n:0,r:0,A:0,M:0,S:null,ca:false,st:'Basic',sk:'No skill. Cannot attack.'},
 {n:1,r:0,A:0,M:0,S:null,ca:true,st:'Basic',sk:'No skill.'},{n:2,r:0,A:0,M:0,S:null,ca:true,st:'Basic',sk:'No skill.'},
 {n:3,r:0,A:0,M:0,S:null,ca:true,st:'Basic',sk:'No skill.'},
 {n:4,r:1,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},{n:5,r:1,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
 {n:6,r:1,A:1,M:1,S:null,ca:true,st:'Basic',sk:'No skill.'},
 {n:7,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},{n:8,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
 {n:9,r:2,A:1,M:2,S:null,ca:true,st:'Basic',sk:'No skill.'},
];

const DECK_AC={
  light:[{n:3,k:'Plus'},{n:2,k:'Repair'},{n:1,k:'Multiply'},{n:1,k:'Reverse'},{n:2,k:'Protect'},{n:2,k:'Cease'},{n:2,k:'Explore'},{n:2,k:'Recover'},{n:3,k:'Counterstrike'},{n:2,k:'Shining Star'},{n:2,k:'Rank Star'},{n:1,k:'Draw Star'},{n:1,k:'Battle Star'},{n:2,k:'Neo Rank Star'}],
  inferno:[{n:2,k:'Battle Star'},{n:1,k:'Rank Star'},{n:2,k:'Neo Rank Star'},{n:3,k:'Plus'},{n:3,k:'Multiply'},{n:2,k:'Reverse'},{n:2,k:'Protect'},{n:1,k:'Recover'},{n:2,k:'Cease'},{n:2,k:'Strike'},{n:2,k:'Counterstrike'},{n:2,k:'Subtract'},{n:2,k:'Burning Star'}],
  blizzard:[{n:3,k:'Repair'},{n:3,k:'Plus'},{n:3,k:'Cease'},{n:2,k:'Protect'},{n:3,k:'Recover'},{n:2,k:'Divide'},{n:2,k:'Counterattack'},{n:2,k:'Counterstrike'},{n:2,k:'Freezing Star'},{n:2,k:'Rank Star'},{n:1,k:'Battle Star'},{n:1,k:'Neo Rank Star'}],
  shadow:[{n:2,k:'Plus'},{n:2,k:'Repair'},{n:1,k:'Reveal'},{n:2,k:'Multiply'},{n:3,k:'Recover'},{n:3,k:'Cease'},{n:1,k:'Strike'},{n:1,k:'Counterattack'},{n:2,k:'Counterstrike'},{n:2,k:'Betray'},{n:2,k:'Shaded Star'},{n:1,k:'Rank Star'},{n:1,k:'Battle Star'},{n:1,k:'Multi-Star'},{n:1,k:'Neo Rank Star'},{n:1,k:'Neo Battle Star'}],
  negative:[{n:2,k:'Plus'},{n:2,k:'Betray'},{n:2,k:'Protect'},{n:3,k:'Repair'},{n:2,k:'Counterstrike'},{n:2,k:'Multiply'},{n:2,k:'Reverse'},{n:2,k:'Subtract'},{n:2,k:'Cease'},{n:2,k:'Minus Star'},{n:2,k:'Rank Star'},{n:1,k:'Battle Star'},{n:2,k:'Neo Rank Star'}],
  deckstructive:[{n:2,k:'Divide'},{n:3,k:'Repair'},{n:2,k:'Counterstrike'},{n:3,k:'Plus'},{n:2,k:'Reverse'},{n:2,k:'Drop Star'},{n:2,k:'Return'},{n:3,k:'Deckstroy'},{n:2,k:'Discard'},{n:1,k:'Rank Star'},{n:1,k:'Draw Star'},{n:1,k:'Battle Star'},{n:1,k:'Neo Rank Star'},{n:1,k:'Neo Draw Star'}],
  maximum:[{n:3,k:'Repair'},{n:3,k:'Counterattack'},{n:3,k:'Plus'},{n:3,k:'Protect'},{n:2,k:'Rank Star'},{n:1,k:'Neo Rank Star'},{n:2,k:'MAX Star'}],
  restorative:[{n:2,k:'Halcyon Star'},{n:3,k:'Plus'},{n:3,k:'Repair'},{n:3,k:'Motivate'},{n:2,k:'Divide'},{n:3,k:'Recover'},{n:1,k:'Cease'},{n:2,k:'Counterstrike'},{n:2,k:'Counterattack'},{n:2,k:'Rank Star'},{n:1,k:'Battle Star'},{n:2,k:'Neo Rank Star'}],
  astute:[{n:2,k:'Studious Star'},{n:2,k:'Plus'},{n:2,k:'Multiply'},{n:1,k:'Muster'},{n:1,k:'Spy'},{n:1,k:'Set'},{n:1,k:'Reveal'},{n:2,k:'Search'},{n:1,k:'Recover'},{n:1,k:'Protect'},{n:1,k:'Return'},{n:1,k:'Cease'},{n:1,k:'Reduce'},{n:1,k:'Divide'},{n:1,k:'Deckstroy'},{n:1,k:'Discard'},{n:1,k:'Counterattack'},{n:1,k:'Counterstrike'},{n:2,k:'Battle Star'},{n:1,k:'Neo Rank Star'},{n:1,k:'Neo Battle Star'}],
  zero:[{n:2,k:'Repair'},{n:1,k:'Wander'},{n:1,k:'Plus'},{n:1,k:'Draw'},{n:1,k:'Reverse'},{n:1,k:'Multiply'},{n:1,k:'Boost'},{n:1,k:'Reanimate'},{n:1,k:'Recover'},{n:1,k:'Protect'},{n:1,k:'Recycle'},{n:2,k:'Cease'},{n:1,k:'Nullify'},{n:2,k:'Counterstrike'},{n:1,k:'Assassinate'},{n:1,k:'Strike'},{n:2,k:'Naught Star'},{n:1,k:'Rank Star'},{n:1,k:'Draw Star'},{n:1,k:'Battle Star'},{n:2,k:'Neo Rank Star'}],
  haste:[{n:2,k:'Track Star'},{n:2,k:'Multiply'},{n:3,k:'Plus'},{n:2,k:'Repair'},{n:2,k:'Cease'},{n:1,k:'Protect'},{n:2,k:'Recover'},{n:1,k:'Divide'},{n:2,k:'Counterstrike'},{n:2,k:'Counterattack'},{n:2,k:'Strike'},{n:1,k:'Rank Star'},{n:1,k:'Battle Star'},{n:1,k:'Multi-Star'},{n:1,k:'Neo Rank Star'},{n:1,k:'Neo Battle Star'}],
  phantom:[{n:2,k:'Haunting Star'},{n:2,k:'Plus'},{n:2,k:'Repair'},{n:2,k:'Multiply'},{n:1,k:'Reverse'},{n:1,k:'Divide'},{n:1,k:'Cease'},{n:2,k:'Recover'},{n:2,k:'Revive'},{n:2,k:'Assassinate'},{n:2,k:'Strike'},{n:2,k:'Counterstrike'},{n:1,k:'Rank Star'},{n:1,k:'Battle Star'},{n:1,k:'Multi-Star'},{n:1,k:'Neo Rank Star'},{n:1,k:'Neo Battle Star'}],
  '7th':[{n:3,k:'Repair'},{n:3,k:'Counterstrike'},{n:3,k:'Protect'},{n:3,k:'Recover'},{n:3,k:'Reverse'},{n:3,k:'Subtract'},{n:1,k:'Rank Star'},{n:1,k:'Battle Star'},{n:2,k:'Seventh Star'},{n:1,k:'Neo Rank Star'}],
};

const AREA_TEXT={
  light:'Shining Justice: While in Deadzone, all Light-class Numerals gain 1 NP. Up to 3x per game, negate a Malevolent Numeral\'s skill by dropping 2 from hand. Once per game, drop your hand (3+ cards) — opponents cannot declare an attack for their next 3 turns. Cannot attack or use Numeral skills on the same turn you use this last effect.',
  inferno:'Wildfire: After 3 turns in your Deadzone, all players lose MP equal to total RP of Numerals they control at the start of every opponent\'s Main Phase. If a Blizzard Numeral skill stops you from attacking, drop a card from hand to negate it. Once per game, drop your hand (3+ cards) — send opponents\' Rank and Flank Zone cards to Deadzone; all other players lose 10 MP.',
  blizzard:'Frozen Tundra: While in Deadzone, all Blizzard-class Numerals gain 1 NP; all Inferno-class Numerals lose 1 NP. If you control 2+ Blizzard Numerals, drop one Blizzard Numeral from hand to negate an opponent\'s attack. If that attack was from Inferno-class, they cannot attack next turn.',
  shadow:'Dark Domain: All Shadow Numerals gain 1 NP while in Deadzone. Once per turn, mill one card — all Benevolent Numerals lose 1 NP until end of turn. Once per exchange, negate the card cost of one Shadow Numeral by dropping cards from hand with NP higher than that Numeral. Once per game, cede your hand (3+ cards) — all opponent Numerals treated as Rank 0 Flanks until end of turn.',
  maximum:'Higher Ground: When in Deadzone on a Maximum Rank Up turn, opponent cannot use Numeral skills until end of turn. Once per game, drop your hand and mill equal cards — all your Maximum Numerals become Rank MAX until end of turn.',
  deckstructive:'Drawbridge: While in Deadzone, if opponent adds cards to hand outside Draw Phase, they mill 1 card per card added. Drop one from hand — opponent drops cards from Deck equal to that card\'s Rank. Once per turn, when any player\'s hand becomes 7+ cards, all drop hands and redraw equal to previous hand. Pay 5 MP — all draw 2 and opponent adds 1 from their Deadzone to hand.',
  negative:'The Lowlands: All other players receive -9 Morale when this card is sent to Deadzone. Cannot be removed from Deadzone. All alternative win conditions are negated. If a player runs out of cards to draw, they shuffle their Discard back into their Deck and continue. Once per game, cede your hand (4+ cards) — all other players\' Numerals switch to negative values until end of turn.',
  restorative:'Halcyon Highlands: While in your Deadzone, all Phantom-class Numerals lose 1 RP. Once per exchange, drop a card from hand and top of Deck — gain 1 MP for each card in your hand. Once per war, send your hand (5+ cards) and top 20 of Deck to the Drop — gain 20 Morale; you cannot attack or use Action Cards for 3 turns.',
  haste:'Fast Track: During your opponent\'s turn, all Haste Numerals gain 1 NP. On the turn you Rank Up to a Haste Numeral, it can attack 3 times if you pay 8 MP. Once per turn, send one from hand and top of Deck to Drop — negate the activation of a Safeguard Action Card. Once per exchange, if you attacked during the opponent\'s turn, your Rank Zone gains 2 NP and can attack again.',
  astute:'The Library: While in your Deadzone, Retaliatory Action Cards that target Astute Numerals inflict 2 MP of damage to their user. Once per turn, pay 3 MP — choose: peek/drop a card from an opponent\'s hand; reorder the top 3 of any Deck; or add an Astute card from your Deck to hand. Once per war, pay 15 MP and drop your hand (4+ cards) — look at the top 7 of all Decks, drop two each, reorder the rest.',
  '7th':'Seven Heaven: While in your Deadzone, a Numeral 7 need not use Chief Flank to be used as a Flank (treated as Rank 2 or lower). Once per turn, choose: gain 2 MP per Numeral 7 on all Battlefields; each player loses 2 MP per non-7 card on their Battlefield; or drop a card and negate a Numeral 7 skill cost / a non-7 skill activation. Once per war, destroy all non-Numeral-7 cards on your Battlefield (min 2) — no one can attack for 7 turns.',
  zero:'Dreadnaught Airship: When sent to your Deadzone, all Numerals on all Battlefields lose all NP until end of that turn. Several once-per-turn effects (discard a card): set a Numeral\'s A to 0; stop an opponent gaining Morale; or pay MP to zero a Numeral until it leaves. Once per war, cede hand NP at least double an opponent\'s Morale — that opponent\'s Morale becomes 0.',
  phantom:'Morbid Cemetery: Does not count toward your Casualty Count. While in your Deadzone, all Phantom & Shadow Numerals gain 1 NP and all Restorative & Light Numerals lose 1 NP. Once per turn, if a Phantom Numeral was sent to your Deadzone by a Retaliatory card or opposing skill, send top of Deck to Drop and return it to the Battlefield. Once-per-war drop effect deals Casualty Draws equal to cards dropped; you cannot attack for 3 turns.',
};
